### ISSUE TITLE
Notification push doesn't work with setUserId

### ISSUE THREAD

**Issue by dmagustina** [microsoft/appcenter-sdk-react-native#575]
### **Description**

I set the user id, then try to use it for sending the push notification, but it never gets received. 

### **Repro Steps**

Please list the steps used to reproduce your issue.

1.In react native AppCenter.setUserId("1234")
2.In swagger: POST /v0.1/apps/{owner_name}/{app_name}/push/notifications
{
  "notification_content": {
    "name": "First Push From App Center",
    "title": "Push From App Center",
    "body": "Hello! Isn't this an amazing notification message?",
    "custom_data": {"key1": "val1", "key2": "val2"}
  },
  "notification_target": {
    "type": "user_ids_target",
    "user_ids": [ "1234" ]
  },
}
3. I also tried sending through the console, didn't work either
4. Sending with the installed id instead works perfectly!

### **Details**

1. Which version of the App Center SDK are you using?
    "appcenter": "1.13.0",
    "appcenter-analytics": "1.13.0",
    "appcenter-crashes": "1.13.0",
    "appcenter-push": "1.13.0",
2. Which OS version did you experience the issue on?
    - Android and Ios
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    -Both emulator and physical
4. What third party libraries are you using?
    - None
5. Run the following command and paste the output below: `react-native info`
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 10.15.3
  Yarn: Not Found
  npm: 6.4.1
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.3 AI-182.5107.16.33.5314842

Packages: (wanted => installed)
  react: ^16.4.1 => 16.8.6
  react-native: ^0.55.3 => 0.55.4

Thank you

**Comment by dhei** [comment]
Hi @dmagustina,

Thanks for getting in touch. Yes we are aware of this issue and it's fixed in v2.0.0 which should be released later this week.

**Comment by FelipeGatti** [comment]
Hello, is this bug already fixed?

**Comment by dhei** [comment]
Hi @FelipeGatti,

This bug should be fixed in v2.0.0 (https://github.com/microsoft/AppCenter-SDK-React-Native/releases/tag/2.0.0). Thanks.

**Comment by bapmrl** [comment]
Hi @dhei,

I'm using `appcenter-push` version `2.0.0` and sending notifications through the console does not appear to work. I did not have the time to test through the Web API.

Here is what we do to set the user ID:

```typescript
const setUserContextEpic: RootEpic = (action$, state$) =>
  action$.pipe(
    filter(
      isActionOf([
        rootActions.liftOff,
        rootActions.logIn.failure,
        rootActions.logIn.success,
        rootActions.logOut,
        rootActions.unauthorized,
      ]),
    ),
    tap(() => {
      const auth = state$.value.authentication
      const id = auth.status === 'loggedIn' ? auth.user.uuid : undefined
      const userId = id === undefined ? null : id
      AppCenter.setUserId(userId)
      Sentry.setUserContext({ id })
    }),
    ignoreElements(),
  )
```

Thank you,

**Comment by guperrot** [comment]
@bapmrl it can take some time to reflect the userId change on the backend, if you push right away after setting userId in your app that will not work.

Also please note that if you restart the application, you need to call AppCenter.setUserId as soon as possible (otherwise the new start of the app will go back to anonymous userId).

If after some time it still does not work, we need to determine if it's SDK issue or backend. For that increase log level to verbose as explained in https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native#adjust-the-log-level and please share the SDK logs with us (there should be http calls and the userId is sent alongside the push log as soon as you call AppCenter.setUserId).

**Comment by Jamminroot** [comment]
Closing thread, feel free to reopen

**Comment by bapmrl** [comment]
Hello @guperrot,

I've tried waiting for one hour and it still does not work with the `userId`. It does work with the `installId`.

Here are the logs (Xcode logs filtered with the _"appcenter"_ text) you've asked for:
```
9-06-03 16:46:33.109509+0200 Beneficiaire[1028:227816] [AppCenter] VERBOSE: -[MSUserIdContext setUserId:]/88 Stored new userId:a141993b-d4d6-4506-b0d9-5b473ef0eeb2 and timestamp: 2019-06-03 14:46:33 +0000.
2019-06-03 16:46:34.206389+0200 Beneficiaire[1028:227812] [AppCenter] VERBOSE: -[MSLogDBStorage loadLogsWithGroupId:limit:excludedTargetKeys:completionHandler:]/189 Load log(s) with id(s) '6' as batch Id:68FCBB22-C22E-468E-A3E6-5FC782F59854
2019-06-03 16:46:34.208052+0200 Beneficiaire[1028:227812] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/242 Sending 1/1 log, group Id: AppCenter, batch Id: 68FCBB22-C22E-468E-A3E6-5FC782F59854, session Id: (null), payload:
    "wrapperSdkName" : "appcenter.react-native",
    "sdkName" : "appcenter.ios",
2019-06-03 16:46:34.208607+0200 Beneficiaire[1028:227812] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/90 URL: https://in.appcenter.ms/logs?api-version=1.0.0
2019-06-03 16:46:34.208861+0200 Beneficiaire[1028:227812] [AppCenter] VERBOSE: -[MSAppCenterIngestion createRequest:]/91 Headers: Install-ID = 1916ACCF-0575-475E-98F6-A1FF291BD3F9, App-Secret = ****************************8188bf17, Content-Type = application/json
2019-06-03 16:46:34.607403+0200 Beneficiaire[1028:227812] [AppCenter] VERBOSE: -[MSHttpIngestion sendCallAsync:]_block_invoke/209 HTTP response received with status code: 200, payload:
2019-06-03 16:46:34.607633+0200 Beneficiaire[1028:227826] [AppCenter] DEBUG: -[MSChannelUnitDefault flushQueue]_block_invoke/263 Log(s) sent with success, batch Id:68FCBB22-C22E-468E-A3E6-5FC782F59854.
2019-06-03 16:46:34.608302+0200 Beneficiaire[1028:227812] [AppCenter] INFO: -[MSHttpIngestion call:completedWithResult:]/258 Removed call id:68FCBB22-C22E-468E-A3E6-5FC782F59854 from pending calls:{
2019-06-03 16:46:34.622812+0200 Beneficiaire[1028:227826] [AppCenter] VERBOSE: +[MSLogDBStorage deleteLogsFromDBWithColumnValues:columnName:inOpenedDatabase:]/330 Deletion of log(s) by id with value(s) '6' succeeded.
```

Thank you,

**Comment by guperrot** [comment]
Hi, the logs are truncated so we cannot read what was sent.
Any chance you can use Charles Proxy or equivalent to capture the HTTPS payloads (after you call setUserId) ?

When you said you use appcenter-push 2.0.0, did you also update all other npm packages to use the same version? It won't work by mix/matching versions.

**Comment by bapmrl** [comment]
Hello @guperrot,

We have the following App Center dependencies in our `package.json` file: `appcenter@2.0.0`, `appcenter-analytics@2.0.0` and `appcenter-push@2.0.0`.

Please find complete logs in the following gist: https://gist.github.com/bapmrl/e88c46f1b5931501c48b27a4cb5d135a.

Thank you,

**Comment by guperrot** [comment]
Is that the only place where you call the API? The SDK does not persist the userId value so after application restart, you will need to re-call AppCenter.setUserId to restore the value (otherwise after restart the push log will be re-sent without userId and that will update the backend). Is that what happens to your app?

**Comment by guperrot** [comment]
Hi, the logs you shared show the app is using version 1.13.0 of the React Native SDK.
Updating the npms is not enough to update native code that it uses (specifically the native Cocoa pods).
Running `react-native link` again is required after updating the npms as explained in https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/react-native#how-to-update-react-native-sdk-to-the-latest-version

In addition to that, please note the userId will also need to be restored after application restart as the SDK does not persist it, AppCenter.setUserId need to be called as soon as possible on restart if userId has to be persisted in your application.

**Comment by bapmrl** [comment]
Hello @guperrot,

That's weird. When I'm using the following Podfile:
```
target 'Beneficiaire' do
  # Pods for Beneficiaire
  platform :ios, '10.0'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'ART',
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  pod 'appcenter-push', path: '../node_modules/appcenter-push/ios'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
end
```

I get the following `Podfile.lock` (with an old version of `AppCenter/Push`):
```
PODS:
  - appcenter (2.0.0):
    - AppCenterReactNativeShared
    - React
  - appcenter-analytics (2.0.0):
    - AppCenter/Analytics
    - AppCenterReactNativeShared
    - React
  - appcenter-push (2.0.0):
    - AppCenter/Push
    - AppCenterReactNativeShared
    - React
  - AppCenter/Analytics (1.14.0):
    - AppCenter/Core
  - AppCenter/Core (1.14.0)
  - AppCenter/Push (1.14.0):
    - AppCenter/Core
  - AppCenterReactNativeShared (1.13.0):
    - AppCenter/Core (= 1.14.0)
  - boost-for-react-native (1.63.0)
  - DoubleConversion (1.1.6)
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - React (0.59.2):
    - React/Core (= 0.59.2)
  - react-native-netinfo (2.0.5):
    - React
  - react-native-splash-screen (3.2.0):
    - React
  - react-native-webview (5.5.0):
    - React
  - React/ART (0.59.2):
    - React/Core
  - React/Core (0.59.2):
    - yoga (= 0.59.2.React)
  - React/CxxBridge (0.59.2):
    - Folly (= 2018.10.22.00)
    - React/Core
    - React/cxxreact
    - React/jsiexecutor
  - React/cxxreact (0.59.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/jsinspector
  - React/DevSupport (0.59.2):
    - React/Core
    - React/RCTWebSocket
  - React/fishhook (0.59.2)
  - React/jsi (0.59.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React/jsiexecutor (0.59.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/cxxreact
    - React/jsi
  - React/jsinspector (0.59.2)
  - React/RCTAnimation (0.59.2):
    - React/Core
  - React/RCTBlob (0.59.2):
    - React/Core
  - React/RCTImage (0.59.2):
    - React/Core
    - React/RCTNetwork
  - React/RCTLinkingIOS (0.59.2):
    - React/Core
  - React/RCTNetwork (0.59.2):
    - React/Core
  - React/RCTSettings (0.59.2):
    - React/Core
  - React/RCTText (0.59.2):
    - React/Core
  - React/RCTWebSocket (0.59.2):
    - React/Core
    - React/fishhook
    - React/RCTBlob
  - RNCAsyncStorage (1.3.3):
    - React
  - RNGestureHandler (1.1.0):
    - React
  - Sentry (4.1.3):
    - Sentry/Core (= 4.1.3)
  - Sentry/Core (4.1.3)
  - SentryReactNative (0.42.0):
    - React
    - Sentry (~> 4.1.3)
  - yoga (0.59.2.React)

DEPENDENCIES:
  - appcenter (from `../node_modules/appcenter/ios`)
  - appcenter-analytics (from `../node_modules/appcenter-analytics/ios`)
  - appcenter-push (from `../node_modules/appcenter-push/ios`)
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - "react-native-netinfo (from `../node_modules/@react-native-community/netinfo`)"
  - react-native-splash-screen (from `../node_modules/react-native-splash-screen`)
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React/ART (from `../node_modules/react-native`)
  - React/Core (from `../node_modules/react-native`)
  - React/CxxBridge (from `../node_modules/react-native`)
  - React/DevSupport (from `../node_modules/react-native`)
  - React/RCTAnimation (from `../node_modules/react-native`)
  - React/RCTImage (from `../node_modules/react-native`)
  - React/RCTLinkingIOS (from `../node_modules/react-native`)
  - React/RCTNetwork (from `../node_modules/react-native`)
  - React/RCTSettings (from `../node_modules/react-native`)
  - React/RCTText (from `../node_modules/react-native`)
  - React/RCTWebSocket (from `../node_modules/react-native`)
  - "RNCAsyncStorage (from `../node_modules/@react-native-community/async-storage`)"
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - SentryReactNative (from `../node_modules/react-native-sentry`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - AppCenter
    - AppCenterReactNativeShared
    - boost-for-react-native
    - Sentry

EXTERNAL SOURCES:
  appcenter:
    :path: "../node_modules/appcenter/ios"
  appcenter-analytics:
    :path: "../node_modules/appcenter-analytics/ios"
  appcenter-push:
    :path: "../node_modules/appcenter-push/ios"
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  React:
    :path: "../node_modules/react-native"
  react-native-netinfo:
    :path: "../node_modules/@react-native-community/netinfo"
  react-native-splash-screen:
    :path: "../node_modules/react-native-splash-screen"
  react-native-webview:
    :path: "../node_modules/react-native-webview"
  RNCAsyncStorage:
    :path: "../node_modules/@react-native-community/async-storage"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  SentryReactNative:
    :path: "../node_modules/react-native-sentry"
  yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  AppCenter: 02c5efe08d3bbab5421ae41d5f7aa7238906b817
  appcenter: 5855258bf713d12f831b018e2e0b1dfc9b7673da
  appcenter-analytics: 81a586968220cd24f114ade296f283407c1710a1
  appcenter-push: 6ae5ffa244f0bd691a5d75544b8773ada7df1b78
  AppCenterReactNativeShared: 00f470c3c17b47718db8733cbe811ccdcfd86282
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  DoubleConversion: bb338842f62ab1d708ceb63ec3d999f0f3d98ecd
  Folly: de497beb10f102453a1afa9edbf8cf8a251890de
  glog: aefd1eb5dda2ab95ba0938556f34b98e2da3a60d
  React: 9d063e2f356c8cd2f54dd550d4507740037cbabe
  react-native-netinfo: 2cfb4a903d90f1beda31c2990a058c51130b53aa
  react-native-splash-screen: 200d11d188e2e78cea3ad319964f6142b6384865
  react-native-webview: 964a008a311579f56d26cdb956d1860ad3d5ccfe
  RNCAsyncStorage: e71d854855f99b1fc46d468858265608b917bbb8
  RNGestureHandler: b65d391f4f570178d657b99a16ec99d09b8656b0
  Sentry: 4e8a17b61ddd116f89536cc81d567fdee1ebca96
  SentryReactNative: 09d5cc89e8bb5d80cfaf3ae11ed2ecb0a47317d2
  yoga: 3768a3026ade0fb46a68f3a31a917cf86bc34fc4

PODFILE CHECKSUM: ec37e89c81bddb10f936da74c950362052de1617

COCOAPODS: 1.6.1
```

But when I'm using the following `Podfile`:
```
target 'Beneficiaire' do
  # Pods for Beneficiaire
  platform :ios, '10.0'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'ART',
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTWebSocket',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'AppCenter/Push', '~> 2.0.1'
  pod 'AppCenter/Analytics', '~> 2.0.1'
  pod 'AppCenterReactNativeShared', '~> 2.0.0'
  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
end
```

I get the following `Podfile.lock` (with the most recent version of `AppCenter/Push`):
```
PODS:
  - appcenter (2.0.0):
    - AppCenterReactNativeShared
    - React
  - appcenter-analytics (2.0.0):
    - AppCenter/Analytics
    - AppCenterReactNativeShared
    - React
  - appcenter-push (2.0.0):
    - AppCenter/Push
    - AppCenterReactNativeShared
    - React
  - AppCenter/Analytics (2.0.1):
    - AppCenter/Core
  - AppCenter/Core (2.0.1)
  - AppCenter/Push (2.0.1):
    - AppCenter/Core
  - AppCenterReactNativeShared (2.0.0):
    - AppCenter/Core (= 2.0.1)
  - boost-for-react-native (1.63.0)
  - DoubleConversion (1.1.6)
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - React (0.59.2):
    - React/Core (= 0.59.2)
  - react-native-netinfo (2.0.5):
    - React
  - react-native-splash-screen (3.2.0):
    - React
  - react-native-webview (5.5.0):
    - React
  - React/ART (0.59.2):
    - React/Core
  - React/Core (0.59.2):
    - yoga (= 0.59.2.React)
  - React/CxxBridge (0.59.2):
    - Folly (= 2018.10.22.00)
    - React/Core
    - React/cxxreact
    - React/jsiexecutor
  - React/cxxreact (0.59.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/jsinspector
  - React/DevSupport (0.59.2):
    - React/Core
    - React/RCTWebSocket
  - React/fishhook (0.59.2)
  - React/jsi (0.59.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React/jsiexecutor (0.59.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React/cxxreact
    - React/jsi
  - React/jsinspector (0.59.2)
  - React/RCTAnimation (0.59.2):
    - React/Core
  - React/RCTBlob (0.59.2):
    - React/Core
  - React/RCTImage (0.59.2):
    - React/Core
    - React/RCTNetwork
  - React/RCTLinkingIOS (0.59.2):
    - React/Core
  - React/RCTNetwork (0.59.2):
    - React/Core
  - React/RCTSettings (0.59.2):
    - React/Core
  - React/RCTText (0.59.2):
    - React/Core
  - React/RCTWebSocket (0.59.2):
    - React/Core
    - React/fishhook
    - React/RCTBlob
  - RNCAsyncStorage (1.3.3):
    - React
  - RNGestureHandler (1.1.0):
    - React
  - Sentry (4.1.3):
    - Sentry/Core (= 4.1.3)
  - Sentry/Core (4.1.3)
  - SentryReactNative (0.42.0):
    - React
    - Sentry (~> 4.1.3)
  - yoga (0.59.2.React)

DEPENDENCIES:
  - appcenter (from `../node_modules/appcenter/ios`)
  - appcenter-analytics (from `../node_modules/appcenter-analytics/ios`)
  - appcenter-push (from `../node_modules/appcenter-push/ios`)
  - AppCenter/Analytics (~> 2.0.1)
  - AppCenter/Push (~> 2.0.1)
  - AppCenterReactNativeShared (~> 2.0.0)
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - "react-native-netinfo (from `../node_modules/@react-native-community/netinfo`)"
  - react-native-splash-screen (from `../node_modules/react-native-splash-screen`)
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React/ART (from `../node_modules/react-native`)
  - React/Core (from `../node_modules/react-native`)
  - React/CxxBridge (from `../node_modules/react-native`)
  - React/DevSupport (from `../node_modules/react-native`)
  - React/RCTAnimation (from `../node_modules/react-native`)
  - React/RCTImage (from `../node_modules/react-native`)
  - React/RCTLinkingIOS (from `../node_modules/react-native`)
  - React/RCTNetwork (from `../node_modules/react-native`)
  - React/RCTSettings (from `../node_modules/react-native`)
  - React/RCTText (from `../node_modules/react-native`)
  - React/RCTWebSocket (from `../node_modules/react-native`)
  - "RNCAsyncStorage (from `../node_modules/@react-native-community/async-storage`)"
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - SentryReactNative (from `../node_modules/react-native-sentry`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  https://github.com/cocoapods/specs.git:
    - AppCenter
    - AppCenterReactNativeShared
    - boost-for-react-native
    - Sentry

EXTERNAL SOURCES:
  appcenter:
    :path: "../node_modules/appcenter/ios"
  appcenter-analytics:
    :path: "../node_modules/appcenter-analytics/ios"
  appcenter-push:
    :path: "../node_modules/appcenter-push/ios"
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  React:
    :path: "../node_modules/react-native"
  react-native-netinfo:
    :path: "../node_modules/@react-native-community/netinfo"
  react-native-splash-screen:
    :path: "../node_modules/react-native-splash-screen"
  react-native-webview:
    :path: "../node_modules/react-native-webview"
  RNCAsyncStorage:
    :path: "../node_modules/@react-native-community/async-storage"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  SentryReactNative:
    :path: "../node_modules/react-native-sentry"
  yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  AppCenter: 6a5ff2fd007b53431259fdd74f91eb3d0dfea3d1
  appcenter: 5855258bf713d12f831b018e2e0b1dfc9b7673da
  appcenter-analytics: 81a586968220cd24f114ade296f283407c1710a1
  appcenter-push: 6ae5ffa244f0bd691a5d75544b8773ada7df1b78
  AppCenterReactNativeShared: a55d6899b99ca2c4904cffd82b2d687626afe251
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  DoubleConversion: bb338842f62ab1d708ceb63ec3d999f0f3d98ecd
  Folly: de497beb10f102453a1afa9edbf8cf8a251890de
  glog: aefd1eb5dda2ab95ba0938556f34b98e2da3a60d
  React: 9d063e2f356c8cd2f54dd550d4507740037cbabe
  react-native-netinfo: 2cfb4a903d90f1beda31c2990a058c51130b53aa
  react-native-splash-screen: 200d11d188e2e78cea3ad319964f6142b6384865
  react-native-webview: 964a008a311579f56d26cdb956d1860ad3d5ccfe
  RNCAsyncStorage: e71d854855f99b1fc46d468858265608b917bbb8
  RNGestureHandler: b65d391f4f570178d657b99a16ec99d09b8656b0
  Sentry: 4e8a17b61ddd116f89536cc81d567fdee1ebca96
  SentryReactNative: 09d5cc89e8bb5d80cfaf3ae11ed2ecb0a47317d2
  yoga: 3768a3026ade0fb46a68f3a31a917cf86bc34fc4

PODFILE CHECKSUM: 5f950d037b2abbb46b46ff13e71902e57f625bb4

COCOAPODS: 1.6.1
```

Shouldn't I be able to declare my dependencies using the following Podfile specs (as described in https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#32-ios-only-integrate-the-ios-sdk-without-react-native-link)?
```
  pod 'appcenter', path: '../node_modules/appcenter/ios'
  pod 'appcenter-analytics', path: '../node_modules/appcenter-analytics/ios'
  pod 'appcenter-push', path: '../node_modules/appcenter-push/ios'
```

Thank you,

**Comment by AnastasiaKubova** [comment]
Hi.
1. Could you please try to build an empty project. If it will be successful then it is maybe Cache issue.
2. Could you please remove next directories:
- pods
- podsfilelog
Try to rebuild your project and provide output logs from pod install.

**Comment by bapmrl** [comment]
Thank you all! It does work after deleting the `ios/Pods` directory and running `pod install --project-directory=ios` again. It was indeed a caching issue.

**Comment by AnastasiaKubova** [comment]
Great. I close the issue. But you can always contact us again if you have any more questions.
